#!/bin/bash
#PBS -A TG-MCA94P014
#PBS -l size=12,walltime=00:0:10
#cd $PBS_O_WORKDIR
# uncomment this ^ for kraken
COMMAND=$1;
MPI=mpirun;
#MPI=${PETSC_DIR}/${PETSC_ARCH}/bin/mpiexec;
RUN="${MPI} -n 3"; 
# for kraken, should be "time aprun -n 12"
# for valgrind, put valgrind after -n 2

GEO="-Nc 1 -Nx 100 -Ny 1 -Nz 1 
-Npmlx 20 -Npmly 0 -Npmlz 0 -LowerPML 0
-hx 0.01 -hy 0.1 -hz 0.2 
-Mx 50 -My 1 -Mz 1 
-epsfile eps1d.txt -fproffile fprof1d.txt
-wa 15.0 -gamma 3.0";

PASSIVE="-wreal 15.7 -wimag -1.07 
-bx 1 -by -1 -bz 1
-kx 0 -ky 0 -kz 0
-BCPeriod -1 -norm 0.01
-passiveout pass
-eps_nev 1 -st_type sinvert  
-st_pc_type lu
-st_pc_factor_mat_solver_package mumps";

CREEPER="-in0 pass0 -in1 pass1
-out0 last14 -out1 last16
-dD 0.05 -Dmax 0.5
-newtonf_tol 1e-7 -thresholdw_tol 1e-7";

SOLVER="-printnewton 0
-pc_factor_mat_solver_package mumps 
-pc_type lu";

OPT="-dD 0.03
-optin thresh
-optout opt";

if [[ $COMMAND = "passive" ]]; then
$RUN ./PassiveOut $GEO $PASSIVE;
elif [[ $COMMAND = "salt" ]]; then
$RUN ./SaltOut $GEO $CREEPER $SOLVER;
elif [[ $COMMAND = "opt" ]]; then
$RUN ./OptOut $GEO $OPT $SOLVER;
elif [[ $COMMAND = "test" ]]; then
mpirun -n 1 ./TestOut;
fi