#!/bin/bash
#PBS -A TG-MCA94P014
#PBS -l size=12,walltime=00:0:10
#cd $PBS_O_WORKDIR
# uncomment this ^ for kraken
COMMAND=$1;
MPI=mpirun;
#MPI=${PETSC_DIR}/${PETSC_ARCH}/bin/mpiexec;
RUN="${MPI} -n 3 ../deps/SaltOut"; 
# for kraken, should be "time aprun -n 12"
# for valgrind, put valgrind after -n 2

GEO="-Nc 1 -Nx 130 -Ny 1 -Nz 1 
-Npmlx 20 -Npmly 0 -Npmlz 0 -LowerPML 0
-hx 0.01 -hy 0.1 -hz 0.2 
-epsfile "eps1d.txt" -fproffile "fprof1d.txt"
-wa 15.0 -gamma 3.0";

PASSIVE="-wreal 15.7 -wimag -1.07 
-bx -1 -by -1 -bz 1
-kx 0 -ky 0 -kz 0 -norm 0.01
-passiveout passodd
-nev 1";

CREEPER="-in0 passodd -in1 passeven
-out0 passodd -out1 passeven
-dD 0.05 -Dmax 1e-15 -output_deps 1
-newtonf_tol 1e-7";

SOLVER="-printnewton 1";

if [[ $COMMAND = "passive" ]]; then
$RUN $GEO $PASSIVE -Dmax 0.0;
elif [[ $COMMAND = "creeper" ]]; then
$RUN $GEO $CREEPER $SOLVER;
elif [[ $COMMAND = "test" ]]; then
mpirun -n 1 ./TestOut;
fi
