#!/bin/bash
#PBS -A TG-MCA94P014
#PBS -l size=12,walltime=00:0:10
#cd $PBS_O_WORKDIR
# uncomment this ^ for kraken
COMMAND=$1;
MPI=mpirun;
#MPI=${PETSC_DIR}/${PETSC_ARCH}/bin/mpiexec;
RUN="${MPI} -n 3 ../deps/SaltOut"; 
# for kraken, should be "time aprun -n 12"
# for valgrind, put valgrind after -n 2

GEO="-Nc 2 -Nx 130 -Ny 130 -Nz 1 
-Npmlx 10 -Npmly 10 -Npmlz 0 -LowerPML 1
-hx 0.046511627906977 -hy 0.046511627906977 -hz 0.2 
-epsfile "epsphc.txt" -fproffile "fphc.txt"
-wa 15.0 -gamma 3.0 -manual_epspml 0 -output_epstilde 0";

PASSIVE="-wreal 1.71 -wimag -0.02
-bx 1 -by -1 -bz 1
-kx 0 -ky 0 -kz 0 -norm 0.01
-passiveout passphc
-nev 4";

CREEPER="-in0 passphc0
-out0 after
-dD 0.01 -Dmax 0.02 -output_deps 0
-newtonf_tol 1e-8 -reuse_lu 1";

SOLVER="-printnewton 1";

if [[ $COMMAND = "passive" ]]; then
$RUN $GEO $PASSIVE -Dmax 0.0;
elif [[ $COMMAND = "creeper" ]]; then
$RUN $GEO $CREEPER $SOLVER;
elif [[ $COMMAND = "test" ]]; then
mpirun -n 1 ./TestOut;
fi
